# Basic server configuration
host: 0.0.0.0
port: 8080
default_timeout: 10

queries:

  # Basic query definition "my-posts" with multiple upstream queries
  my-posts:
    - url: https://jsonplaceholder.typicode.com/posts/1   # upstream APIs to fetch
      fields:
        - title                                           # fields to aggregate
        - body

    - url: https://jsonplaceholder.typicode.com/posts/2
      fields:
        another-title: .title                             # re-mapping of fields
        another-body: .body
        nested: .some.nested.object                       # nested objects, arrays, ...
        array: .some.indexed[42].item
        everything: .

    - url: https://jsonplaceholder.typicode.com/posts
      fields:
        total_posts: . | length                           # complex jq filters
        sum_of_ids: map(.id) | add
        rounded: .[42].userId | round
        rounded_2decimals: (.[42].userId * 100 | round) / 100
